### ISSUE TITLE
ERROR: IOS Mpcheckout.startCheckout

### ISSUE THREAD

**Issue by black10manda** [Gonzaa25/mpcheckout#11]
Hola, gracias por compartir tu librería  me funciona genial en Andorid solo quería ver si me puedes resolver una duda.
Al momento de ejecutar el metodo 
`final result = await mp.startCheckout(_pref);`
en IOS me regresa el siguiente error
<img width="991" alt="Captura de pantalla 2023-01-30 a la(s) 7 52 58 p m" src="https://user-images.githubusercontent.com/45544069/215639600-bcfdfd9c-0783-43b2-b59f-e12ff587b562.png">

esta es la configuración  de mi archivo `AppDelegate.swift`

```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  var navigationController: UINavigationController?;

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    // Add this line before GeneratedPluginRegistrant
    let flutterViewController: FlutterViewController = window?.rootViewController as! FlutterViewController

    // This line is added by the Flutter App Generator
    GeneratedPluginRegistrant.register(with: self)

    // Add these lines after GeneratedPluginRegistrant
    self.navigationController = UINavigationController(rootViewController: flutterViewController);
    self.navigationController?.setNavigationBarHidden(true, animated: false);

    self.window = UIWindow(frame: UIScreen.main.bounds);
    self.window.rootViewController = self.navigationController;
    self.window.makeKeyAndVisible();
    // End of edit

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

si me pudieras ayudar te lo agradecería

**Comment by gonzalogauto** [comment]
> Hola, gracias por compartir tu librería me funciona genial en Andorid solo quería ver si me puedes resolver una duda. Al momento de ejecutar el metodo `final result = await mp.startCheckout(_pref);` en IOS me regresa el siguiente error <img alt="Captura de pantalla 2023-01-30 a la(s) 7 52 58 p m" width="991" src="https://user-images.githubusercontent.com/45544069/215639600-bcfdfd9c-0783-43b2-b59f-e12ff587b562.png">
> 
> esta es la configuración de mi archivo `AppDelegate.swift`
> 
> `import UIKit import Flutter
> 
> @UIApplicationMain @objc class AppDelegate: FlutterAppDelegate { var navigationController: UINavigationController?;
> 
> override func application( _ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? ) -> Bool { // Add this line before GeneratedPluginRegistrant let flutterViewController: FlutterViewController = window?.rootViewController as! FlutterViewController
> 
> ```
> // This line is added by the Flutter App Generator
> GeneratedPluginRegistrant.register(with: self)
> 
> // Add these lines after GeneratedPluginRegistrant
> self.navigationController = UINavigationController(rootViewController: flutterViewController);
> self.navigationController?.setNavigationBarHidden(true, animated: false);
> 
> self.window = UIWindow(frame: UIScreen.main.bounds);
> self.window.rootViewController = self.navigationController;
> self.window.makeKeyAndVisible();
> // End of edit
> 
> return super.application(application, didFinishLaunchingWithOptions: launchOptions)
> ```
> 
> } }`
> 
> si me pudieras ayudar te lo agradecería

Hola!! como estas? muchas gracias por tu consulta primero que nada. Puedes indicarme en que version de flutter y dart estas? necesitaria el resultado de los siguientes comandos `flutter doctor` / `flutter --version` / `dart --version`

**Comment by black10manda** [comment]
si claro con mucho gusto 
<img width="631" alt="Captura de pantalla 2023-02-02 a la(s) 8 55 45 p m" src="https://user-images.githubusercontent.com/45544069/216501844-6056bb32-fa3d-41e8-a3cf-ee6f9222669c.png">

**Comment by gonzalogauto** [comment]
> si claro con mucho gusto <img alt="Captura de pantalla 2023-02-02 a la(s) 8 55 45 p m" width="631" src="https://user-images.githubusercontent.com/45544069/216501844-6056bb32-fa3d-41e8-a3cf-ee6f9222669c.png">

Muchas gracias! Creo tener el error identificado, ya estoy subiendo una nueva version para que puedas intentarlo nuevamente v0.0.9. en unos minutos/horas deberia estar disponible en [pub.dev](https://pub.dev/packages/mpcheckout). Espero tu confirmacion de que esta resuelto para asi poder dar cierre al issue.

**Comment by gonzalogauto** [comment]
> > si claro con mucho gusto <img alt="Captura de pantalla 2023-02-02 a la(s) 8 55 45 p m" width="631" src="https://user-images.githubusercontent.com/45544069/216501844-6056bb32-fa3d-41e8-a3cf-ee6f9222669c.png">
> 
> Muchas gracias! Creo tener el error identificado, ya estoy subiendo una nueva version para que puedas intentarlo nuevamente v0.0.9. en unos minutos/horas deberia estar disponible en [pub.dev](https://pub.dev/packages/mpcheckout). Espero tu confirmacion de que esta resuelto para asi poder dar cierre al issue.

@black10manda te recomiendo que una vez instales la nueva version v0.0.9 pares la app si es que la tenes abierta en debug mode y corras `flutter clean && flutter pub get` para limpiar todo y levantar la app de cero.

**Comment by black10manda** [comment]
muchas gracias por tu ayuda, ya instale la nueva version pero al mometo de ejecutar la app me aparece este error

<img width="922" alt="Captura de pantalla 2023-02-02 a la(s) 11 30 36 p m" src="https://user-images.githubusercontent.com/45544069/216520609-7ce1741a-536c-438c-b33f-c9c7cb58fbb8.png">

**Comment by gonzalogauto** [comment]
> muchas gracias por tu ayuda, ya instale la nueva version pero al mometo de ejecutar la app me aparece este error
> 
> <img alt="Captura de pantalla 2023-02-02 a la(s) 11 30 36 p m" width="922" src="https://user-images.githubusercontent.com/45544069/216520609-7ce1741a-536c-438c-b33f-c9c7cb58fbb8.png">

Creo que deberias setear el min version a IOS 11 para poder buildearla

**Comment by black10manda** [comment]
una pregunta en android el pago se procesa bien pero en ios al abrir el checkout me aparece este error

<img width="341" alt="Captura de pantalla 2023-02-03 a la(s) 3 08 54 p m" src="https://user-images.githubusercontent.com/45544069/216711348-d0f25767-0a7e-4ae6-95c6-56aae10321f8.png">

esta es mi preference

`
final Preference _pref = Preference(
        items: [
          Item(title: 'puduld', quantity: 1, unitPrice: 120, currencyId: "MXN"),
        ],
        paymentMethods: PaymentMethods(
          excludedPaymentTypes: [
            ExcludedPaymentTypes(id: 'ticket'),
            ExcludedPaymentTypes(id: 'atm'),
          ],
        ),
        payer: Payer(email: 'chems@chem.com', name: 'juan', surname: 'chem'),
      );
`

**Comment by gonzalogauto** [comment]
> una pregunta en android el pago se procesa bien pero en ios al abrir el checkout me aparece este error
> 
> <img alt="Captura de pantalla 2023-02-03 a la(s) 3 08 54 p m" width="341" src="https://user-images.githubusercontent.com/45544069/216711348-d0f25767-0a7e-4ae6-95c6-56aae10321f8.png">
> 
> esta es mi preference
> 
> `final Preference _pref = Preference( items: [ Item(title: 'puduld', quantity: 1, unitPrice: 120, currencyId: "MXN"), ], paymentMethods: PaymentMethods( excludedPaymentTypes: [ ExcludedPaymentTypes(id: 'ticket'), ExcludedPaymentTypes(id: 'atm'), ], ), payer: Payer(email: 'chems@chem.com', name: 'juan', surname: 'chem'), );`

Perdon por tanta demora pero lamentablemente no tuve tiempo para volver a mantener este package. Actualmente el mismo se encuentra actualizado pero perdió el soporte para IOS debido a que MercadoPago cerró el acceso al repo del SDK para ios px-ios. He intentado contactarme con ellos pero aun no tengo respuesta alguna sobre el motivo o alguna alternativa que me permita reactivarlo. Todo esto es mencionado en el nuevo ISSUE https://github.com/gonzalogauto/mpcheckout/issues/17

**Comment by gonzalogauto** [comment]
Procedo a cerrar este issue debido a que el SDK de mercadopago para IOS anteriormente llamado px-ios fue removido por parte de mercadopago ( mas info en #17 ). Si surgen mas dudas al respecto o inconvenientes no dudes en contactarme nuevamente.
