### ISSUE TITLE
Android 12 and higher required to specify an explicit value for `android:exported`

### ISSUE THREAD

**Issue by KriacoesMobile** [Gonzaa25/mpcheckout#6]
Hello my friend first thanks for sharing this library, I already used it in another flutter project but the application used android 11 at most now I'm using another project and implemented it again but now the android version is 12 and it requires the android:exported information to be declared in the AndroidManifest.xml would have some way of declare since the library does not have AndroidManifest.xml?

```
Error:
android:exported needs to be explicitly specified for element <activity#com.mercadopago.android.px.internal.features.checkout.CheckoutActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.
```

What I did manually to compile and use the library was to declare the changed activity in my own application manifest, **but I don't know if it's the correct way or the best way**, but I managed to run it after that, thanks in advance for the help.

My solution now:

```
<activity android:name="com.mercadopago.android.px.internal.features.checkout.CheckoutActivity" android:exported="true"/>
```

**Comment by gonzalogauto** [comment]
Hi @KriacoesMobile !! Thanks for all the explanation about your issue. To run on android 12 you need to add android:exported="true" in you own flutter app manifest like this. Add exported flag in all `<activity>` and that's it. 
That's a requirement inside you flutter app.

![Screen Shot 2022-08-02 at 11 18 12](https://user-images.githubusercontent.com/44684314/182397108-cc133105-da5a-445b-ac4d-60de676897e8.png)
.

**Comment by KriacoesMobile** [comment]
Hello my friend, thank you very much for the help, then I was on the right path, thank you
